version: '3'

services:

  php:
    build : 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source:/var/www/code
    depends_on:
      - db

  ngix:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./source:/var/www/code
      - ./vhost:/etc/nginx/conf.d
    depends_on:
      - php
  
  adminer:
    image: adminer
    ports:
      - 90:8080
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user